// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy2mzk3BxTCw91CQR9SV_pQtfHSollXyQ',
    appId: '1:140123757478:web:f459f880777bed8f4dcd67',
    messagingSenderId: '140123757478',
    projectId: 'ecommerce-11f8e',
    authDomain: 'ecommerce-11f8e.firebaseapp.com',
    storageBucket: 'ecommerce-11f8e.appspot.com',
    measurementId: 'G-RE21XBYCJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6DrJPcQIvHhuTEz8mkecloMzDVVx2x2I',
    appId: '1:140123757478:android:a038ffddf997be8d4dcd67',
    messagingSenderId: '140123757478',
    projectId: 'ecommerce-11f8e',
    storageBucket: 'ecommerce-11f8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiKwkhfF2cbvxa84odfZFhRLAfyUNsC8A',
    appId: '1:140123757478:ios:d78b5eb5798cd7974dcd67',
    messagingSenderId: '140123757478',
    projectId: 'ecommerce-11f8e',
    storageBucket: 'ecommerce-11f8e.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiKwkhfF2cbvxa84odfZFhRLAfyUNsC8A',
    appId: '1:140123757478:ios:d78b5eb5798cd7974dcd67',
    messagingSenderId: '140123757478',
    projectId: 'ecommerce-11f8e',
    storageBucket: 'ecommerce-11f8e.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy2mzk3BxTCw91CQR9SV_pQtfHSollXyQ',
    appId: '1:140123757478:web:3e79002d3725d7b84dcd67',
    messagingSenderId: '140123757478',
    projectId: 'ecommerce-11f8e',
    authDomain: 'ecommerce-11f8e.firebaseapp.com',
    storageBucket: 'ecommerce-11f8e.appspot.com',
    measurementId: 'G-QCGVCRQ7X2',
  );
}
